version: '3'
services:
  web:
    # docker build -f Dockerfile.dev -t sscheffler.eu/frontend .
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      # docker run -p 4300:3000 -v /app/node_modules -v $(pwd):/app sscheffler.eu/frontend
      - "4200:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev    
    volumes:
      - /app/node_modules
      - .:/app
    # Override command in container
    command: ["npm","run","test"]
    
