version: '3'
services:
  web:
    # docker build -f Dockerfile.dev -t sscheffler.eu/frontend .
    build: 
      context: .
      dockerfile: Dockerfile.dev
    # docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app sscheffler.eu/frontend
    ports:
      - "4200:3000"
    volumes:
      - /app/node_modules
      - .:/app
